export type BookTickerItem = {
  slug: string;
  title: string;
  author: string;
  coverSrc: string;
  sourceUrl: string;
  accessUrl: string;
  accessLabel: string;
};

const amazonSearch = (query: string) =>
  `https://www.amazon.com/s?k=${encodeURIComponent(query)}`;

export const bookTickerItems: BookTickerItem[] = [
  {
    slug: "obesity-code",
    title: "The Obesity Code",
    author: "Jason Fung",
    coverSrc: "/book-covers/obesity-code.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/12398696-L.jpg?default=false",
    accessUrl: amazonSearch("The Obesity Code Jason Fung"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "diabetes-code",
    title: "The Diabetes Code",
    author: "Jason Fung",
    coverSrc: "/book-covers/diabetes-code.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/14851433-L.jpg",
    accessUrl: amazonSearch("The Diabetes Code Jason Fung"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "dr-bernsteins-diabetes-solution",
    title: "Dr. Bernstein's Diabetes Solution",
    author: "Richard K. Bernstein",
    coverSrc: "/book-covers/dr-bernsteins-diabetes-solution.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/7931436-L.jpg",
    accessUrl: amazonSearch("Dr. Bernstein's Diabetes Solution Richard K. Bernstein"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "cbt-workbook-mental-health",
    title: "The CBT Workbook for Mental Health",
    author: "Simon Rego PsyD and Sarah Fader",
    coverSrc: "/book-covers/cbt-workbook-mental-health.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/12442906-L.jpg",
    accessUrl: amazonSearch(
      "The CBT Workbook for Mental Health Evidence-Based Exercises to Transform Negative Thoughts and Manage Your Well-Being",
    ),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "a-fearless-heart",
    title: "A Fearless Heart",
    author: "Thupten Jinpa",
    coverSrc: "/book-covers/a-fearless-heart.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/8884352-L.jpg",
    accessUrl: amazonSearch(
      "A Fearless Heart How the Courage to Be Compassionate Can Transform Our Lives Thupten Jinpa",
    ),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "easy-way-stop-smoking-canadian-edition",
    title: "Allen Carr's Easy Way to Stop Smoking: Canadian Edition",
    author: "Allen Carr",
    coverSrc: "/book-covers/easy-way-stop-smoking-canadian-edition.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/12997583-L.jpg",
    accessUrl: amazonSearch(
      "Allen Carr's Easy Way to Stop Smoking: Canadian Edition Allen Carr",
    ),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "why-we-get-sick",
    title: "Why We Get Sick",
    author: "Ben Bikman",
    coverSrc: "/book-covers/why-we-get-sick.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/10394551-L.jpg",
    accessUrl: amazonSearch("Why We Get Sick Ben Bikman"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "complete-guide-to-fasting",
    title: "The Complete Guide to Fasting",
    author: "Jason Fung",
    coverSrc: "/book-covers/complete-guide-to-fasting.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/14685632-L.jpg",
    accessUrl: amazonSearch("The Complete Guide to Fasting Jason Fung"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "brain-energy",
    title: "Brain Energy",
    author: "Christopher M. Palmer",
    coverSrc: "/book-covers/brain-energy.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/13162337-L.jpg",
    accessUrl: amazonSearch("Brain Energy Christopher M. Palmer"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "carnivore-diet",
    title: "The Carnivore Diet",
    author: "Shawn Baker",
    coverSrc: "/book-covers/carnivore-diet.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/14845371-L.jpg?default=false",
    accessUrl: amazonSearch("The Carnivore Diet Shawn Baker"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "atkins-new-diet-revolution",
    title: "Atkins Diet",
    author: "Robert C. Atkins",
    coverSrc: "/book-covers/atkins-new-diet-revolution.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/6874833-L.jpg?default=false",
    accessUrl: amazonSearch("Dr. Atkins New Diet Revolution Robert C. Atkins"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "protein-power",
    title: "Protein Power",
    author: "Michael R. Eades and Mary Dan Eades",
    coverSrc: "/book-covers/protein-power.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/368019-L.jpg",
    accessUrl: amazonSearch("Protein Power Michael R. Eades Mary Dan Eades"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "why-we-get-fat",
    title: "Why We Get Fat",
    author: "Gary Taubes",
    coverSrc: "/book-covers/why-we-get-fat.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/6675596-L.jpg",
    accessUrl: amazonSearch("Why We Get Fat Gary Taubes"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "good-calories-bad-calories",
    title: "Good Calories, Bad Calories",
    author: "Gary Taubes",
    coverSrc: "/book-covers/good-calories-bad-calories.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/8027557-L.jpg",
    accessUrl: amazonSearch("Good Calories Bad Calories Gary Taubes"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "art-and-science-low-carb-living",
    title: "The Art and Science of Low Carbohydrate Living",
    author: "Jeff S. Volek and Stephen Phinney",
    coverSrc: "/book-covers/art-and-science-low-carb-living.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/12179002-L.jpg?default=false",
    accessUrl: amazonSearch(
      "The Art and Science of Low Carbohydrate Living Jeff Volek Stephen Phinney",
    ),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "delay-dont-deny",
    title: "Delay, Don't Deny",
    author: "Gin Stephens",
    coverSrc: "/book-covers/delay-dont-deny.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/10191598-L.jpg?default=false",
    accessUrl: amazonSearch("Delay, Don't Deny Gin Stephens"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "fast-feast-repeat",
    title: "Fast. Feast. Repeat.",
    author: "Gin Stephens",
    coverSrc: "/book-covers/fast-feast-repeat.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/10175103-L.jpg?default=false",
    accessUrl: amazonSearch("Fast. Feast. Repeat. Gin Stephens"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "oldest-cure-in-the-world",
    title: "The Oldest Cure in the World",
    author: "Steve Hendricks",
    coverSrc: "/book-covers/oldest-cure-in-the-world.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/13848606-L.jpg?default=false",
    accessUrl: amazonSearch("The Oldest Cure in the World Steve Hendricks"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "eat-fat-and-grow-slim",
    title: "Eat Fat and Grow Slim (1957)",
    author: "David F. Cottrell",
    coverSrc: "/book-covers/eat-fat-and-grow-slim.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/14950162-L.jpg",
    accessUrl: amazonSearch("Eat Fat and Grow Slim David F. Cottrell"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "high-fat-nutrition",
    title: "High Fat Nutrition (1978)",
    author: "Frederick J. Stare and Elisabeth A. Lloyd (ed.)",
    coverSrc: "/book-covers/high-fat-nutrition.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/6457421-L.jpg?default=false",
    accessUrl: amazonSearch(
      "High Fat Nutrition Frederick J. Stare Elisabeth A. Lloyd",
    ),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "fasting-cure",
    title: "The Fasting Cure",
    author: "Upton Sinclair",
    coverSrc: "/book-covers/fasting-cure.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/1990585-L.jpg",
    accessUrl: amazonSearch("The Fasting Cure Upton Sinclair"),
    accessLabel: "Buy on Amazon",
  },
  {
    slug: "letter-on-corpulence",
    title: "Letter on Corpulence, Addressed to the Public",
    author: "William Banting",
    coverSrc: "/book-covers/letter-on-corpulence.jpg",
    sourceUrl: "https://covers.openlibrary.org/b/id/11531875-L.jpg",
    accessUrl: amazonSearch(
      "Letter on Corpulence, Addressed to the Public William Banting",
    ),
    accessLabel: "Buy on Amazon",
  },
];
